version: 2.0

jobs:
    build:
        docker:
            - image: circleci/openjdk:8
        steps:
            - checkout
            - restore_cache:
                keys:
                    - gradle-{{ checksum "build.gradle" }}
            - run: ./gradlew clean
            - run: ./gradlew jar
            - run: ./gradlew jacocoTestReport
            - save_cache:
                paths:
                    - ~/.gradle
                key: gradle-{{ checksum "build.gradle" }}
            - store_artifacts:
                path: build/libs
                destination: libs

